apiVersion: v1
kind: Service
metadata:
  name: ms-alertas
  namespace: muni-valle-sol
  labels:
    app: ms-alertas
spec:
  selector:
    app: ms-alertas
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
